#print("Hi Luara")
#print("Hello world")
#print("The itsy bitsy spider climbed up the waterspout")
#print()
#print("Down came the rain and washed the spider out")
#print("The itsy bitsy spider\nclimbed up the waterspout")
#print()
#print("Down came the rain\nand washed the spider out")
#print("Luara\'Froes")
#print("Hello\r world")
#print("Hello\t world")
#print("Hello\n world")
#print("The itsy bitsy spider", "climbed up", "the waterspout")
#print("My name is", "Python.", end=" ")
#print("Monty Python")
#print("My name is", "Python.", end="\n")
#print("Monty Python")
#print("My", "name", "is", sep="_", end="*")
#print("Monty", "Python.", sep="*", end="*\n")
#print("My_name_is*Monty*Python*")
#print("Programming", "Essentials", "in", sep="***", end="...")
#print("Python")
#print("Programming", "Essentials", "in", sep="\n", end="...")
#print("Python")
#print("I'm", "learning", "Python")
#print ('"I\'m"\n""learning""\n"""Python"""')
#print(True > False)
#print(True<False)
#print(2 ** 3)
#print(2. ** 3)
#print(2 ** 3.)
#print(2. ** 3.)
#print(6/3)
#print(6/3.)
#print(6./3)
#print(6./3.)
#print(7/3)
#print(-6//4)
#print(6.//-4)
#Adiós_Señora = 3
var = 1
account_balance = 1000.0
client_name = 'John Doe'
print(var, account_balance, client_name)
print(var)
var = 2
print (var)